### Category Embedding

In [68]:
import pandas as pd

In [69]:
df=pd.read_csv("/kaggle/input/advancehousepriceprediction/train.csv",usecols=["SalePrice","MSSubClass","MSZoning","LotFrontage","LotArea","Street","YearBuilt","LotShape","1stFlrSF","2ndFlrSF"]).dropna()

In [70]:
df.shape

(1201, 10)

In [71]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


### Features include both categorical and continuous values
Print the column name with uniques values

In [73]:
for i in df.columns:
    print("Column name {} and unique values are {} ".format(i,len(df[i].unique())))

Column name MSSubClass and unique values are 15 
Column name MSZoning and unique values are 5 
Column name LotFrontage and unique values are 110 
Column name LotArea and unique values are 869 
Column name Street and unique values are 2 
Column name LotShape and unique values are 4 
Column name YearBuilt and unique values are 112 
Column name 1stFlrSF and unique values are 678 
Column name 2ndFlrSF and unique values are 368 
Column name SalePrice and unique values are 597 


### Feature will low values are Categorical and the other are continuous

## Changing the date time feature

In [74]:
import datetime
datetime.datetime.now().year

2023

In [75]:
# getting total year by subtracting the present year with the year built
df["Total years"]=datetime.datetime.now().year-df["YearBuilt"]

In [76]:
df.drop("YearBuilt",axis=1,inplace=True)

In [77]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total years'],
      dtype='object')

In [78]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  1stFlrSF  \
0          60       RL         65.0     8450   Pave      Reg       856   
1          20       RL         80.0     9600   Pave      Reg      1262   
2          60       RL         68.0    11250   Pave      IR1       920   
3          70       RL         60.0     9550   Pave      IR1       961   
4          60       RL         84.0    14260   Pave      IR1      1145   

   2ndFlrSF  SalePrice  Total years  
0       854     208500           20  
1         0     181500           47  
2       866     223500           22  
3       756     140000          108  
4      1053     250000           23

In [79]:
# Creating Categorical Features
cat_features=["MSSubClass","MSZoning","Street","LotShape"]
out_features="SalePrice"

In [80]:
df["MSSubClass"].unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  80, 160,  75, 180,
        40,  85])

### Label Encoding for one feature

In [81]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
lbl_encoders["MSSubClass"]=LabelEncoder()
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])

array([5, 0, 5, ..., 6, 0, 0])

In [82]:
lbl_encoders

{'MSSubClass': LabelEncoder()}

In [83]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature])

In [84]:
df


MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0              5         3         65.0     8450       1         3       856   
1              0         3         80.0     9600       1         3      1262   
2              5         3         68.0    11250       1         0       920   
3              6         3         60.0     9550       1         0       961   
4              5         3         84.0    14260       1         0      1145   
...          ...       ...          ...      ...     ...       ...       ...   
1455           5         3         62.0     7917       1         3       953   
1456           0         3         85.0    13175       1         3      2073   
1457           6         3         66.0     9042       1         3      1188   
1458           0         3         68.0     9717       1         3      1078   
1459           0         3         75.0     9937       1         3      1256   

      2ndFlrSF  SalePrice  Total years  
0          854     208500           20  
1            0     181500           47  
2          866     223500           22  
3          756     140000          108  
4         1053     250000           23  
...        ...        ...          ...  
1455       694     175000           24  
1456         0     210000           45  
1457      1152     266500           82  
1458         0     142125           73  
1459         0     147500           58  

[1201 rows x 10 columns]

In [85]:
## Stacking and converting into Tensors
cat_features=np.stack([df['MSSubClass'],df["MSZoning"],df["Street"],df["LotShape"]],1)
cat_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]])

In [86]:
## Convert the numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [87]:
# # Create a continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass","MSZoning","Street","LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i)
    

In [88]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total years']

In [89]:
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float)
cont_values

tensor([[   65.,  8450.,   856.,   854.,    20.],
        [   80.,  9600.,  1262.,     0.,    47.],
        [   68., 11250.,   920.,   866.,    22.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    82.],
        [   68.,  9717.,  1078.,     0.,    73.],
        [   75.,  9937.,  1256.,     0.,    58.]])

In [90]:
cont_values.dtype

torch.float32

In [91]:
# Dependent feature
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)# reshape is given to make it into a 2D tensor
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int64  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int64  
 5   LotShape     1201 non-null   int64  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   Total years  1201 non-null   int64  
dtypes: float64(1), int64(9)
memory usage: 103.2 KB


In [93]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [94]:
len(df['MSSubClass'].unique())

15

In [95]:
df.shape

(1201, 10)

#### Embedding size for categorical columns

In [96]:
cat_dims=[len (df[col].unique()) for col in ["MSSubClass","MSZoning","Street","LotShape"]]

In [97]:
cat_dims

[15, 5, 2, 4]

### Dimensions will help embedding layer to decide what input layer should be used and based on that what will be the output.

In [98]:
len(df["MSSubClass"].unique())

15

In [99]:
# embedding can be used only categorical columns
cat_dims

[15, 5, 2, 4]

In [100]:
# Thumb rule--> Output Dimension should be set based on the input dimension(min(50,feature dimension/2))
embedding_dim=[(x,min(50,(x+1)//2)) for x in cat_dims]

In [101]:
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [102]:
import torch
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [103]:
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [104]:
cat_featuresz=cat_features[:4]
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [105]:
pd.set_option('display.max_rows',500)
embedding_val=[]
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i]))

In [106]:
embedding_val

[tensor([[ 0.1160, -0.5836,  0.1142,  ...,  1.0497, -0.1206, -1.8167],
         [-0.8677, -1.3736,  0.3053,  ..., -0.6119, -0.8595,  0.8906],
         [ 0.1160, -0.5836,  0.1142,  ...,  1.0497, -0.1206, -1.8167],
         ...,
         [ 1.2494,  0.4159,  1.7399,  ...,  1.5180,  1.6180, -0.8075],
         [-0.8677, -1.3736,  0.3053,  ..., -0.6119, -0.8595,  0.8906],
         [-0.8677, -1.3736,  0.3053,  ..., -0.6119, -0.8595,  0.8906]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423],
         ...,
         [-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423]], grad_fn=<EmbeddingBackward0>),
 tensor([[-2.0546],
         [-2.0546],
         [-2.0546],
         ...,
         [-2.0546],
         [-2.0546],
         [-2.0546]], grad_fn=<EmbeddingBackward0>),
 tensor([[0.8648, 0.6523],
         [0.8648, 0.6523],
         [0.6751, 0.8799],

In [107]:
z=torch.cat(embedding_val,1)
z

tensor([[ 0.1160, -0.5836,  0.1142,  ..., -2.0546,  0.8648,  0.6523],
        [-0.8677, -1.3736,  0.3053,  ..., -2.0546,  0.8648,  0.6523],
        [ 0.1160, -0.5836,  0.1142,  ..., -2.0546,  0.6751,  0.8799],
        ...,
        [ 1.2494,  0.4159,  1.7399,  ..., -2.0546,  0.8648,  0.6523],
        [-0.8677, -1.3736,  0.3053,  ..., -2.0546,  0.8648,  0.6523],
        [-0.8677, -1.3736,  0.3053,  ..., -2.0546,  0.8648,  0.6523]],
       grad_fn=<CatBackward0>)

In [108]:
# Implement Dropupout to avoid overfitting
dropout=nn.Dropout(.4)

In [109]:
final_embed=dropout(z)
final_embed

tensor([[ 0.0000, -0.0000,  0.1903,  ..., -3.4244,  0.0000,  1.0871],
        [-0.0000, -0.0000,  0.5088,  ..., -3.4244,  1.4413,  1.0871],
        [ 0.0000, -0.9726,  0.0000,  ..., -3.4244,  1.1252,  0.0000],
        ...,
        [ 2.0824,  0.6931,  2.8998,  ..., -0.0000,  1.4413,  1.0871],
        [-1.4462, -2.2894,  0.5088,  ..., -3.4244,  0.0000,  0.0000],
        [-1.4462, -2.2894,  0.5088,  ..., -0.0000,  0.0000,  1.0871]],
       grad_fn=<MulBackward0>)

In [110]:
##### Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
class FeedForwardNN(nn.Module):

    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        n_emb = sum((out for inp,out in embedding_dim))
        n_in = n_emb + n_cont
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [111]:
len(cont_features)

5

In [112]:
torch.manual_seed(100)
model=FeedForwardNN(embedding_dim,len(cont_features),1,[100,50],p=0.4)

In [113]:
model

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

### Define Loss and Optimizer


In [114]:
model.parameters

<bound method Module.parameters of FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)>

In [115]:
loss_function=nn.MSELoss()# later convert to root mean square error
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [116]:
df.shape

(1201, 10)

In [117]:
cont_values

tensor([[   65.,  8450.,   856.,   854.,    20.],
        [   80.,  9600.,  1262.,     0.,    47.],
        [   68., 11250.,   920.,   866.,    22.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    82.],
        [   68.,  9717.,  1078.,     0.,    73.],
        [   75.,  9937.,  1256.,     0.,    58.]])

In [118]:
cont_values.shape


torch.Size([1201, 5])

### Train Test Split

In [119]:
batch_size=1200
test_size=int(batch_size*0.15)
train_categorical=cat_features[:batch_size-test_size]
test_categorical=cat_features[batch_size-test_size:batch_size]
train_cont=cont_values[:batch_size-test_size]
test_cont=cont_values[batch_size-test_size:batch_size]
y_train=y[:batch_size-test_size]
y_test=y[batch_size-test_size:batch_size]

In [120]:
len(train_categorical),len(test_categorical),len(train_cont),len(test_cont),len(y_train),len(y_test)

(1020, 180, 1020, 180, 1020, 180)

In [121]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model(train_categorical,train_cont)
    loss=torch.sqrt(loss_function(y_pred,y_train)) ### RMSE
    final_losses.append(loss)
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch number: 1 and the loss : 200496.75
Epoch number: 11 and the loss : 200493.46875
Epoch number: 21 and the loss : 200489.140625
Epoch number: 31 and the loss : 200482.640625
Epoch number: 41 and the loss : 200473.25
Epoch number: 51 and the loss : 200461.375
Epoch number: 61 and the loss : 200446.421875
Epoch number: 71 and the loss : 200429.375
Epoch number: 81 and the loss : 200407.96875
Epoch number: 91 and the loss : 200383.453125
Epoch number: 101 and the loss : 200355.3125
Epoch number: 111 and the loss : 200322.390625
Epoch number: 121 and the loss : 200291.40625
Epoch number: 131 and the loss : 200252.1875
Epoch number: 141 and the loss : 200206.640625
Epoch number: 151 and the loss : 200162.65625
Epoch number: 161 and the loss : 200112.234375
Epoch number: 171 and the loss : 200059.140625
Epoch number: 181 and the loss : 200006.0
Epoch number: 191 and the loss : 199946.984375
Epoch number: 201 and the loss : 199881.625
Epoch number: 211 and the loss : 199815.703125
Epoch n

In [ ]:
## Validate the Test data
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical,test_cont)
    loss=torch.sqrt(loss_function(y_pred,y_test))
print('RMSE : {}'.format(loss))



In [ ]:
data_verify=pd.DataFrame(y_test.tolist(),columns=["Test"])

In [ ]:
data_predicted=pd.DataFrame(y_pred.tolist(),columns=["Prediction"])

In [ ]:
data_verify

In [122]:
data_predicted

Prediction
0     89229.789062
1    199307.093750
2    112400.070312
3    216944.843750
4    199181.250000
5    224995.312500
6    155935.890625
7    304209.968750
8    142459.343750
9    379086.750000
10   211524.140625
11   219887.593750
12   194130.109375
13   106413.398438
14   211500.687500
15   109234.851562
16   253314.750000
17   115561.078125
18   306057.500000
19    74646.648438
20   190404.343750
21    96284.476562
22    86273.710938
23   173132.015625
24   194345.218750
25   195073.562500
26   150494.906250
27   365060.843750
28   140671.546875
29   157746.625000
30    69001.750000
31   134688.750000
32   266698.906250
33    81074.992188
34   241613.312500
35   200034.515625
36   132564.968750
37   118892.585938
38   160469.343750
39   105219.648438
40   267584.156250
41   327314.156250
42    92067.648438
43   123548.007812
44   200279.312500
45    91232.523438
46   101527.875000
47   143783.093750
48   105040.101562
49   243533.625000
50   133918.234375
51   352450.281250
52   221461.031250
53   152701.625000
54   267534.406250
55   201980.421875
56   137344.187500
57   117479.476562
58   271004.156250
59   190580.031250
60   345547.343750
61    98957.296875
62   214143.515625
63   242088.265625
64   183681.718750
65   114072.773438
66   164694.500000
67   265868.312500
68    85374.976562
69   269689.312500
70    80061.359375
71    77627.093750
72    95993.757812
73   262147.937500
74   212866.437500
75   223510.562500
76   120323.554688
77   101588.812500
78   131586.593750
79   107795.851562
80   151706.031250
81   125666.570312
82    66511.273438
83   230928.078125
84   128468.390625
85   101288.960938
86   152676.906250
87   147831.031250
88   155108.468750
89   111823.281250
90   270306.500000
91   100572.742188
92   171837.562500
93   138036.796875
94   132176.468750
95   416947.875000
96   230123.250000
97   364307.750000
98   239038.453125
99   260866.437500
100  181673.343750
101  174275.171875
102  233670.843750
103   97866.242188
104  264601.031250
105  147515.156250
106  167742.703125
107  242297.468750
108  275111.906250
109  244637.937500
110   73090.210938
111  125714.054688
112   57343.988281
113  200842.625000
114   95488.359375
115  137606.156250
116  109639.000000
117  117808.945312
118  368458.843750
119  261060.375000
120  305865.156250
121  106631.796875
122  188359.421875
123  125239.632812
124  101454.898438
125  139167.906250
126  193407.281250
127  317218.031250
128   91160.414062
129  170163.203125
130  112869.125000
131  102881.882812
132  210760.093750
133  179236.031250
134  261372.218750
135  107554.648438
136  155688.281250
137  121016.203125
138  147623.390625
139  244895.734375
140  231484.359375
141  158285.375000
142   92219.210938
143  314442.562500
144  136248.031250
145  272937.000000
146  134278.765625
147  141717.765625
148  138621.625000
149  114438.492188
150  142110.015625
151  139051.140625
152  222015.375000
153  141316.531250
154   96786.539062
155  232521.906250
156  100372.570312
157  210208.015625
158  157432.171875
159  178131.281250
160  112906.539062
161  350833.781250
162  116640.960938
163  192252.781250
164  196418.687500
165  355906.218750
166  216540.500000
167   96977.742188
168  267875.281250
169  113029.304688
170   81120.953125
171  106251.085938
172  290975.968750
173   93107.000000
174  167439.875000
175  181290.484375
176  182014.750000
177  251558.109375
178  221583.609375
179  102569.273438

In [123]:
final_output=pd.concat([data_verify,data_predicted],axis=1)
final_output

Test     Prediction
0    130000.0   89229.789062
1    138887.0  199307.093750
2    175500.0  112400.070312
3    195000.0  216944.843750
4    142500.0  199181.250000
5    265900.0  224995.312500
6    224900.0  155935.890625
7    248328.0  304209.968750
8    170000.0  142459.343750
9    465000.0  379086.750000
10   178000.0  211524.140625
11   186500.0  219887.593750
12   129500.0  194130.109375
13   119000.0  106413.398438
14   244000.0  211500.687500
15   130000.0  109234.851562
16   165400.0  253314.750000
17   127500.0  115561.078125
18   301500.0  306057.500000
19    99900.0   74646.648438
20   190000.0  190404.343750
21   151000.0   96284.476562
22   128900.0   86273.710938
23   180500.0  173132.015625
24   181000.0  194345.218750
25   183900.0  195073.562500
26   122000.0  150494.906250
27   378500.0  365060.843750
28   144000.0  140671.546875
29   177000.0  157746.625000
30   139000.0   69001.750000
31   137000.0  134688.750000
32   237000.0  266698.906250
33    68400.0   81074.992188
34   227000.0  241613.312500
35   180000.0  200034.515625
36   150500.0  132564.968750
37   139000.0  118892.585938
38   169000.0  160469.343750
39   132500.0  105219.648438
40   278000.0  267584.156250
41   281000.0  327314.156250
42   119500.0   92067.648438
43   107500.0  123548.007812
44   162900.0  200279.312500
45   115000.0   91232.523438
46   138500.0  101527.875000
47   155000.0  143783.093750
48   140000.0  105040.101562
49   160000.0  243533.625000
50   154000.0  133918.234375
51   290000.0  352450.281250
52   232000.0  221461.031250
53   130000.0  152701.625000
54   325000.0  267534.406250
55   202500.0  201980.421875
56   138000.0  137344.187500
57   147000.0  117479.476562
58   335000.0  271004.156250
59   203000.0  190580.031250
60   333168.0  345547.343750
61   119000.0   98957.296875
62   206900.0  214143.515625
63   295493.0  242088.265625
64   208900.0  183681.718750
65   111000.0  114072.773438
66   156500.0  164694.500000
67   190000.0  265868.312500
68    82500.0   85374.976562
69   147000.0  269689.312500
70    55000.0   80061.359375
71    79000.0   77627.093750
72   130500.0   95993.757812
73   256000.0  262147.937500
74   176500.0  212866.437500
75   227000.0  223510.562500
76   132500.0  120323.554688
77   100000.0  101588.812500
78   125500.0  131586.593750
79   125000.0  107795.851562
80   167900.0  151706.031250
81   135000.0  125666.570312
82    52500.0   66511.273438
83   200000.0  230928.078125
84   128500.0  128468.390625
85   123000.0  101288.960938
86   155000.0  152676.906250
87   177000.0  147831.031250
88   155835.0  155108.468750
89   108500.0  111823.281250
90   283463.0  270306.500000
91   122000.0  100572.742188
92   200000.0  171837.562500
93   171000.0  138036.796875
94   134900.0  132176.468750
95   410000.0  416947.875000
96   170000.0  230123.250000
97   315000.0  364307.750000
98   189000.0  239038.453125
99   260000.0  260866.437500
100  156932.0  181673.343750
101  144152.0  174275.171875
102  193000.0  233670.843750
103  127000.0   97866.242188
104  232000.0  264601.031250
105  105000.0  147515.156250
106  165500.0  167742.703125
107  274300.0  242297.468750
108  250000.0  275111.906250
109  239000.0  244637.937500
110   91000.0   73090.210938
111  117000.0  125714.054688
112   83000.0   57343.988281
113  167500.0  200842.625000
114   58500.0   95488.359375
115  157000.0  137606.156250
116  105000.0  109639.000000
117  125500.0  117808.945312
118  250000.0  368458.843750
119  136000.0  261060.375000
120  377500.0  305865.156250
121  131000.0  106631.796875
122  235000.0  188359.421875
123  124000.0  125239.632812
124  123000.0  101454.898438
125  163000.0  139167.906250
126  246578.0  193407.281250
127  281213.0  317218.031250
128  137500.0   91160.414062
129  138000.0  170163.203125
130  137450.0  112869.125000
131  120000.0  102881.882812
132  193000.0  210760.093750
133  193879.0  179236.031250
134  282922.0  261372.218750
135  105000.0  107554.648438
136  275000.0  155688.281250
137  13

In [124]:
final_output['Difference']=final_output['Test']-final_output['Prediction']
final_output.head()

Test     Prediction    Difference
0  130000.0   89229.789062  40770.210938
1  138887.0  199307.093750 -60420.093750
2  175500.0  112400.070312  63099.929688
3  195000.0  216944.843750 -21944.843750
4  142500.0  199181.250000 -56681.250000

In [125]:
# Saving the Model
torch.save(model,"Houseprice.pt")

In [126]:
torch.save(model.state_dict(),'HouseWeights.pt')

In [127]:
## Loading the saved Model
embs_size=[(15, 8), (5, 3), (2, 1), (4, 2)]
model1=FeedForwardNN(embs_size,5,1,[100,50],p=0.4)

In [128]:
model1.load_state_dict(torch.load('HouseWeights.pt'))

<All keys matched successfully>

In [129]:
model1.eval()

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)